# Generated by Django 4.1.1 on 2022-10-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ehousingapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="ProfileImage",
            field=models.FileField(default="avatar.png", upload_to="profiles/"),
        ),
    ]
